### PR TITLE
Adds web entrypoint

### LINKED ISSUE #208: "AsyncLocalStorage" is not exported by "__vite-browser-external"
Trying to build the langgraph project using vite, getting this error

"AsyncLocalStorage" is not exported by "__vite-browser-external", imported by "node_modules/@langchain/langgraph/dist/setup/async_local_storage.js".

### PR DESCRIPTION
**Pull request by jacoblee93**
Creates separate entrypoint for LangGraph classes that does not include async local storage.

I'm not sure why the initialize call was so nested - I think may have been unnecessary, tracing seems fine.

We will want to document this carefully and also update prebuilt components to explicitly pass config around to avoid the need for a `prebuilt/web` entrypoint.

CC @nfcampos @andrewnguonly @dqbd

Fixes #208 and #81

### CODE REVIEW

**Comment by andrewnguonly** [comment]
What's the impact of this? Does this means LangGraph classes can be used in a browser context?

**Comment by jacoblee93** [comment]
> What's the impact of this? Does this means LangGraph classes can be used in a browser context?

Exactly, that's the big one that doesn't support `async_hooks`.

For prebuilt components, we should make sure we pass `config` manually and avoid importing from the primary `index.js` entrypoint from now on.

**Review by nfcampos — APPROVED** [review]

**Comment by adamgit** [comment]
Fresh install of langsmith, following the API examples word for word, crashes apparently because of the same issue this was created to resolve.

No langgraph is being imported directly - it's all being brought-in by langsmith. But there's no mention in the langsmith docs that I can see for how to workaround this.

Was this workaround only created for direct use of langgraph? i.e. langsmith etc needs to be manually patched to make it work in browser?

**Comment by jacoblee93** [comment]
Depends on what you're importing but if it's `traceable` then it will not work in the browser due to async hooks usage.

We've been careful to isolate it for LangGraph/LangChain and could do the same for LangSmith but figured it was more niche since in most cases you wouldn't want to leak your API key on the frontend - what is your use case?

**Comment by adamgit** [comment]
Personally: local development / VPN, and evaluation. If it's known / 
deliberate that it can't work in browser then it would be good if someone 
documented that - ideally in the features pages but at least: in the 
install docs.

**Comment by Scra3** [comment]
Hi, I'm using the web entry point, and I'm wondering how to use the “interrupt” function as it's not exported from “web”? Thanks 🙏

**Comment by jacoblee93** [comment]
It's currently unsupported in `web` as it requires AsyncLocalStorage features :(

**Comment by Scra3** [comment]
Thank you for the answer, do you know if there is an alternative?

**Comment by jacoblee93** [comment]
You can use a `NodeInterrupt` and then update state before resuming:

https://langchain-ai.github.io/langgraphjs/how-tos/#human-in-the-loop

https://langchain-ai.github.io/langgraphjs/how-tos/dynamic_breakpoints/

CC @benjamincburns

**Pull request merged**
